version: "3.9"
services:
  # web server
  #===============================#
  web-server:
    image: web-server:latest
    ports: 
      - "80:80"
      #- "443:443"
    depends_on:
      - product-api
      - cart-api
    restart: unless-stopped
  #===============================#
  # message broker
  #===============================#
  #message-broker:
  #  image: rabbitmq:latest
  #  expose:
  #    - "5672"
  #  restart: unless-stopped
  #  environment:
  #    - RABBITMQ_DEFAULT_USER=mqu
  #    - RABBITMQ_DEFAULT_PASS=mqp
  #===============================#
  # product service
  #===============================#
  product-api:
    image: product-api:latest
    expose: 
      - "80"
    depends_on:
  #    - message-broker
      - product-db
    restart: unless-stopped
  product-db:
    image: postgres:latest
    expose:
      - "5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=testpw
      - POSTGRES_USER=testu
      - POSTGRES_DB=testdb
  #  volumes:
  #    - product-db-store:/var/lib/postgresql/data
  #===============================#
  # cart service
  #===============================#
  cart-api:
    image: cart-api:latest
    expose: 
      - "80"
    depends_on:
    #  - message-broker
      - cart-db
    restart: unless-stopped
  cart-db:
    image: mongo:latest
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=testu
      - MONGO_INITDB_ROOT_PASSWORD=testpw
      - MONGO_INITDB_DATABASE=cart
    restart: unless-stopped
  #===============================#
#volumes:
#  product-db-store: