version: "3.9"
services:
  # gateway
  #===============================#
  gateway:
    image: gateway:latest
    ports: 
      - "80:80"
      #- "443:443"
    depends_on:
      - product-server
      - order-server
    restart: unless-stopped
  #===============================#
  # message broker
  #===============================#
  #message-broker:
  #  image: rabbitmq:latest
  #  expose:
  #    - "5672"
  #  restart: unless-stopped
  #  environment:
  #    - RABBITMQ_DEFAULT_USER=mqu
  #    - RABBITMQ_DEFAULT_PASS=mqp
  #===============================#
  # product service
  #===============================#
  product-server:
    image: product-server:latest
    expose: 
      - "80"
    depends_on:
  #    - message-broker
      - product-database
    restart: unless-stopped
  product-database:
    image: postgres:latest
    expose:
      - "5432"
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=7sfEkfYS5WyNNE2P
      - POSTGRES_USER=adapter
      - POSTGRES_DB=products
  #  volumes:
  #    - product-db-store:/var/lib/postgresql/data
  #===============================#
  # cart service
  #===============================#
  order-server:
    image: order-server:latest
    expose: 
      - "80"
    depends_on:
    #  - message-broker
      - order-database
    restart: unless-stopped
  order-database:
    image: mongo:latest
    expose:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=adapter
      - MONGO_INITDB_ROOT_PASSWORD=a9snJYSsDm8rSAHG
      - MONGO_INITDB_DATABASE=order
    restart: unless-stopped
  #===============================#
#volumes:
#  product-db-store: